services:
  identity:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/identity/src           # Mount the local src directory
      - ./target:/identity/target       # Mount the local target directory
      - ./mvnw:/identity/mvnw           # Mount the mvnw script
      - ./pom.xml:/identity/pom.xml     # Mount the pom.xml if needed
    ports:
      - "8091:8091"                     # Map port 8091 to the host