services:
  app:
    build: .
    ports:
      - "8085:8085"
    volumes:
      - .:/gateway-api  # Ensure this matches your Dockerfile's WORKDIR
      - ~/.m2:/root/.m2  # Cache Maven dependencies
    command: ./mvnw spring-boot:run
    environment:
      - SPRING_PROFILES_ACTIVE=dev