spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Babymonitor
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081


jwt:
  auth:
    converter:
      resource-id: babymonitor-client-api
      principle-attribute: preferred_username

