# frontend/Dockerfile
# step 1: Build
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN rm -rf /app/dist /app/node_modules /app/.cache
RUN npm run build
RUN npm run serve

# step 2: run with NGINX
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]