name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main'1

jobs:
  snyk_test:
    name: Snyk Security Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Authenticate with Snyk
        run: snyk auth 2713790a-b8ac-4b1b-871d-fcfea2e017f1

      - name: Run Snyk Test
        run: snyk test

      - name: Monitor Snyk Results
        run: snyk monitor

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}  # Replace with your secret for Docker Hub username
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}  # Replace with your secret for Docker Hub password

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./twedditfront
          file: ./twedditfront/Dockerfile
          push: true
          tags: ${{ secrets.CI_REGISTRY_USER }}/tweddit-frontend:latest

      - name: Build and Push API Gateway Image
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          push: true
          tags: ${{ secrets.CI_REGISTRY_USER }}/tweddit-api-gateway:latest

      - name: Build and Push Tweet Service Image
        uses: docker/build-push-action@v5
        with:
          context: ./TweetService
          file: ./TweetService/Dockerfile
          push: true
          tags: ${{ secrets.CI_REGISTRY_USER }}/tweddit-tweetservice:latest

      - name: Build and Push Notification Service Image
        uses: docker/build-push-action@v5
        with:
          context: ./NotificationService
          file: ./NotificationService/Dockerfile
          push: true
          tags: ${{ secrets.CI_REGISTRY_USER }}/tweddit-notifiservice:latest

      - name: Build and Push Identity Service Image
        uses: docker/build-push-action@v5
        with:
          context: ./identityService
          file: ./identityService/Dockerfile
          push: true
          tags: ${{ secrets.CI_REGISTRY_USER }}/tweddit-identityService:latest