name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main'

jobs:
  build-and-push:
    runs-on: self-hosted  # GitHub Actions will run on an Ubuntu runner

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Build Docker image for frontend
      run: |
        cd twedditfront
        docker build -t frontend:latest .
        docker push frontend:latest
    - name: Build Docker image for API Gateway
      run: |
        cd ApiGateway
        docker build -t api-gateway:latest .
        docker push api-gateway:latest
    - name: Build Docker image for tweet service
      run: |
        cd TweetService
        docker build -t tweetservice:latest .
        docker push tweetservice:latest
    - name: Build Docker image for notification service
      run: |
        cd NotificationService
        docker build -t notifiservice:latest .
        docker push notifiservice:latest
    - name: Deploy to kube
      run: |
        ./deploy-to-minikube.ps1

