name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # GitHub Actions will run on an Ubuntu runner

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Build Docker image for frontend
      run: |
        cd twedditfront
        docker build -t localhost:4000/drayma/frontend:latest .
        docker push localhost:4000/drayma/frontend:latest
    - name: Build Docker image for API Gateway
      run: |
        cd ../api-gateway
        docker build -t localhost:5000/drayma/api-gateway:latest .
        docker push localhost:5000/drayma/api-gateway:latest
    - name: Build Docker image for tweet service
      run: |
        cd ../NotificationService
        docker build -t localhost:5001/drayma/notifiservice:latest .
        docker push localhost:5001/drayma/notifiservice:latest
    - name: Build Docker image for notification service
      run: |
        cd ../TweetService
        docker build -t localhost:5002/drayma/tweetservice:latest .
        docker push localhost:5002/drayma/tweetservice:latest

